### PR TITLE
The private token is no longer given

### PR DESCRIPTION
**Pull request by tiferrei**
Removed the private token from the User request, as it is no longer given by the API.

### CODE REVIEW

**Comment by pietbrauer** [comment]
Can you please link to the GitLab PullRequest that is removing this from the API?

**Comment by tiferrei** [comment]
To be honest I didn't find it through the evolution docs, I was really working on adding more resources when I noticed this, but it's even updated on the API documentation's example response: https://docs.gitlab.com/ce/api/users.html#current-user

``` json
{
  "id": 1,
  "username": "john_smith",
  "email": "john@example.com",
  "name": "John Smith",
  "state": "active",
  "avatar_url": "http://localhost:3000/uploads/user/avatar/1/index.jpg",
  "web_url": "http://localhost:3000/u/john_smith",
  "created_at": "2012-05-23T08:00:58Z",
  "is_admin": false,
  "bio": null,
  "location": null,
  "skype": "",
  "linkedin": "",
  "twitter": "",
  "website_url": "",
  "organization": "",
  "last_sign_in_at": "2012-06-01T11:41:01Z",
  "confirmed_at": "2012-05-23T09:05:22Z",
  "theme_id": 1,
  "color_scheme_id": 2,
  "projects_limit": 100,
  "current_sign_in_at": "2012-06-02T06:36:55Z",
  "identities": [
    {"provider": "github", "extern_uid": "2435223452345"},
    {"provider": "bitbucket", "extern_uid": "john_smith"},
    {"provider": "google_oauth2", "extern_uid": "8776128412476123468721346"}
  ],
  "can_create_group": true,
  "can_create_project": true,
  "two_factor_enabled": true,
  "external": false
}
```

As you can see it was removed, used to be the last field on the response, I believe.

**Comment by tiferrei** [comment]
Because remember that GitLab is drifting away from Private Tokens, they want the user to manually create a personal access token for each app, so it would no longer make sense to show a resource that most users don't use.

**Comment by pietbrauer** [comment]
I think the reason was another https://github.com/gitlabhq/gitlabhq/commit/727dff3f158b9ef852b2b014d4efe0abd69a23d0

**Comment by tiferrei** [comment]
Probably, it's also a quite evident security risk.

**Comment by tiferrei** [comment]
@pietbrauer Can you please restart the CI jobs on this one? According to the logs it seems like a temporary error with missing simulators, should be fixed by now.

**Pull request merged**
