### PR TITLE
Swift 3.0

### PR DESCRIPTION
**Pull request by pietbrauer**

### CODE REVIEW

**Comment by tiferrei** [comment]
Shouldn't we remove the `Nocilla` framework, as we no longer use it for tests?

**Comment by pietbrauer** [comment]
Feel free to make PullRequest to `master`. Its just a missing reference after all.

**Comment by tiferrei** [comment]
Also, sorry, git beginner question, where am I supposed to do the changes to? Imagine I add a commits api request, should I do it in the master branch, swift2.3 or swift3.0? Or all of them? Like, how do we keep all the branches up-to-date?

**Comment by pietbrauer** [comment]
My [previous comment](https://github.com/nerdishbynature/TanukiKit/pull/16#issuecomment-228325024) literally says `master`? I [also highlighted](https://github.com/nerdishbynature/TanukiKit/pull/14#issuecomment-228310862) that the `swift-*` branches are being rebased while changes on master occur.  Please [see the rebase docs](https://git-scm.com/docs/git-rebase) if you don't know what exactly that means.

**Comment by tiferrei** [comment]
@pietbrauer, we have a small problem, on both 3.0 and 2.3 branches, the `podspec` is still pointing to `RequestKit` 0.3.0, so it builds perfectly as source code, but when using `TanukiKit` in another project as a cocoa pod, it kinda breaks the `Routers` as the syntax changed a bit with the new `RequestKit` so it fails to compile. And to get things even worse, we can't specific branches for dependencies in the `podspec`, it only accepts releases.

For example, errors like:
`Use of undeclared type 'RequestKitURLSession'` and `Type 'PublicKeyRouter' does not conform to protocol 'Router'` as this version still required the `params` to be `[String : String]`

**Pull request merged**
