### PR TITLE
GitLabKit –> TanukiKit

### PR DESCRIPTION
**Pull request by tiferrei**
Issue #8 and previous Pull Request #10.

Guess that third time's the charm, this should actually make it through.

### CODE REVIEW

**Comment by tiferrei** [comment]
@pietbrauer, if I do a pull request for each file added, this might take around 5 pull requests just for the ones I have currently ready, would you still prefer to stick to 1 PR per file? Also, what kind of tests would you like for the `GET` requests?

**Comment by tiferrei** [comment]
Also, I was trying to create tests for the requests, even if it was just to check if the request reached `.Success` or `.Failure`, and I provoked a typical 404 but the test still passed, what do you think of this?

``` swift
class UserTests: XCTestCase {
    func testToGetUserData() {
        let config = PrivateTokenConfiguration("12345")
        TanukiKit(config).me() { response in
            switch response {
            case .Success(let user):
                print(user)
                XCTAssertNotNil(user)
            case .Failure(let error):
                print(error)
                XCTAssert(false, "❗UserTests.testToGetUserData() –> Should not get an error.")
            }
        }
    } 
}
```

**Comment by pietbrauer** [comment]
It is not about opening a new pull request for each file. Want is the norm is to make a pull request for each logical change, so:
1. PR for the GitlabKit -> TanukiKit change
2. PR for the `repositories` -> `projects` Change
3. PR for the `builds`

**Comment by tiferrei** [comment]
Yes yes, that does make sense, good news, haven't checked for `RequestKit` but `TanukiKit` only changes a line or 2 on the config for `swift3` :)

**Pull request merged**
