### PR TITLE
login –> username

### PR DESCRIPTION
**Pull request by tiferrei**
As discussed on #31

### CODE REVIEW

**Review by pietbrauer — APPROVED** [review]

**Comment by pietbrauer** [comment]
Superb!

**Comment by tiferrei** [comment]
@pietbrauer: I think we're ready for a major release now?

**Comment by pietbrauer** [comment]
I'm all for it. Can you prepare a change log?

**Comment by tiferrei** [comment]
Sure thing!

**Comment by tiferrei** [comment]
@pietbrauer: Done, change log is in the release draft.

**Comment by pietbrauer** [comment]
Cool, thanks a lot for helping! I [just published 0.5.0](https://github.com/nerdishbynature/TanukiKit/releases/tag/0.5.0) following your draft

**Comment by tiferrei** [comment]
My pleasure! 👍

**Pull request merged**
